config/routes.rb
Katerit::Application.routes.draw do
  resources :orders

  resources :pictures

  resources :dishes

  resources :categories

  resources :roles

  devise_for :users
  
  resources :users do
    resources :orders
  end

  resources :restaurants do
    resources :dishes
  end

  root :to => 'restaurants#index'

  get "/search", :controller => "search", :action => "index"

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  attr_accessible :address, :email, :name, :phone, :website, :user_id

  has_many :dishes 
  has_many :pictures

  belongs_to :users

  validates_uniqueness_of :name

  def to_param
  	"#{id}-#{name.parameterize}"
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  load_and_authorize_resource

  before_filter :authenticate_user!, :except => [:index, :show]


  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @restaurants }
    end
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @restaurant = Restaurant.find(params[:id].to_i)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @restaurant }
    end
  end

  # GET /restaurants/new
  # GET /restaurants/new.json
  def new
    @restaurant = Restaurant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @restaurant }
    end
  end

  # GET /restaurants/1/edit
  def edit
    @restaurant = Restaurant.find(params[:id].to_i)
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(params[:restaurant])

    #Assign the new restaurant with an owner_id of the person who created it
    @restaurant.user_id = current_user.id

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render json: @restaurant, status: :created, location: @restaurant }
      else
        format.html { render action: "new" }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /restaurants/1
  # PUT /restaurants/1.json
  def update
    @restaurant = Restaurant.find(params[:id].to_i)

    respond_to do |format|
      if @restaurant.update_attributes(params[:restaurant])
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant = Restaurant.find(params[:id].to_i)
    @restaurant.destroy

    respond_to do |format|
      format.html { redirect_to restaurants_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<div class="row">
	<div class="span3 offset5">
		<% if can? :create, Restaurant %>
    		<%= link_to 'New Restaurant', new_restaurant_path , :class => 'btn btn-primary'%>
    	<% else %>
    		<%= link_to 'New Order', new_order_path , :class => 'btn btn-primary'%>
		<% end %>
    </div>
</div>

<% @restaurants.each_with_index do |restaurant, i| %>
    <% if i%3 == 0 %>
        <div class="row">
    <% end %>

    <div class="span4"><%= link_to image_tag(restaurant.pictures.first.url, :class => 'img-rounded') , restaurant%></div>

    <% if i%3 == 2 %>
        </div>
    <% end %>
<% end %>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @restaurant.name %>
</p>

<p>
  <b>Address:</b>
  <%= @restaurant.address %>
</p>

<p>
  <b>Phone:</b>
  <%= @restaurant.phone %>
</p>

<p>
  <b>Email:</b>
  <%= mail_to @restaurant.email %>
</p>

<p>
  <b>Website:</b>
  <%= link_to @restaurant.website, @restaurant.website %>
</p>

<p>
  <b>Owner:</b>
  <%= User.find_by_id(@restaurant.user_id).name %>
</p>

<p>
  <b>Dishes:</b>
  <ul>
  <% @restaurant.dishes.each do |dish| %>
    <li><%= link_to dish.name, restaurant_dish_url(@restaurant, dish) %></li>
  <% end %>
  </ul>
</p>

<% if can? :edit, Restaurant %>
<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<% end %>
<%= link_to 'Back', restaurants_path %>

<div id="myCarousel" class="carousel slide">
  <div class="carousel-inner">
    <% @restaurant.pictures.each_with_index do |picture,i| %>
      <div class="item <%= 'active' if i == 0%>"><%= image_tag picture.url, :class => "img-rounded" %></div>
    <% end %>
  </div>
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a></div>
</div>