config/routes.rb
Katerit::Application.routes.draw do
  resources :orders

  resources :pictures

  resources :dishes

  resources :categories

  resources :roles

  devise_for :users
  
  resources :users do
    resources :orders
  end

  resources :restaurants do
    resources :dishes
  end

  root :to => 'restaurants#index'

  get "/search", :controller => "search", :action => "index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>kater.it</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar">
	<div class="navbar-inner">
		<%= link_to "kater.it", "/", :class=>"brand" %>
		<ul class="nav">
			<li><%= link_to "Restaurants", restaurants_url %></li>
			<li><%= link_to "Dishes", dishes_url %></li>
			<% if user_signed_in? %>
				<li><%= link_to "Orders", orders_url %></li>
			<% else %>
				<li><%= link_to "Orders", new_order_url %></li>
			<% end %>
		</ul>
		<ul class="nav pull-right">
			<% if user_signed_in? %>
				<li><%= link_to "Hello #{current_user.email}", user_url(current_user.id) %></li>
				<li class="pull-right"><%= link_to "Sign Out", destroy_user_session_url, :method => :delete %></li>
			<% else %>
				<li class="pull-right"><%= link_to "Sign Up", new_user_registration_url %></li>
				<li class="pull-right"><%= link_to "Sign In", new_user_session_url %></li>
			<% end %>
		</ul>
		<form class="navbar-search pull-right">
			<input id="input-search" type="text" class="search-query" placeholder="Search">
		</form>
	</div>
</div>

<div class="container">
	<%= yield %>
</div>

</body>
</html>